"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[character]
success_symbol = "[ï‚¤ ](bold green)"
error_symbol = "[ï‚¤ ](bold red)"

[cmd_duration]
format = "ï¨š[$duration]($style) "

[directory]
truncation_length = 8
truncate_to_repo = false
truncation_symbol = ".../"

[git_branch]
symbol = "ğŸŒ± "
truncation_symbol = ""

[git_commit]
commit_hash_length = 4
tag_symbol = "ğŸ”– "

[git_state]
merge = "ï™ MERGING"
cherry_pick = "ğŸ’ PICKING"
style = "bold red"

[git_metrics]
disabled = false

[git_status]
ahead = "ï¢ "
behind = "ï£ "
diverged = "ï¢ï£ "
up_to_date = ""
untracked = "ï„¨"
stashed = "ïš’ "
modified = "ï€ "
staged = "ï§ "
deleted = "ï¯Š"
style = "bold yellow"

[battery]
full_symbol = "ï•¸ "
charging_symbol = "ï–ƒ "
discharging_symbol = "ï®Š "
