"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[cmd_duration]
format = "ó°”Ÿ [$duration]($style)"
style = "bold yellow"

[directory]
truncation_length = 8
truncate_to_repo = false
truncation_symbol = ".../"

[git_branch]
symbol = "ğŸŒ± "
truncation_symbol = ""

[git_commit]
commit_hash_length = 4
tag_symbol = "ğŸ”–"

[git_state]
merge = "ï™ MERGING"
cherry_pick = "ğŸ’ PICKING"
style = "bold red"

[git_metrics]
disabled = false

[git_status]
ahead = "ï¢"
behind = "ï£"
diverged = "ï¢ï£"
up_to_date = "ï®"
untracked = "ï„¨"
stashed = "ó°¸§"
modified = "ï€"
staged = "ï§"
deleted = "ï’"
style = "bold blue"

[battery]
full_symbol = "ó±Š£"
charging_symbol = "ó± ´"
discharging_symbol = "ó°‚ƒ"
